######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 7 22:17:22 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
TRANSLATIONS = yy_zh.ts
CODECFORSRC     = UTF-8
SOURCES += main.cpp mainwindow.cpp
